version: '3'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 blog.wsgi:application
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: nombre_basededatos
      POSTGRES_USER: nombre_usuario
      POSTGRES_PASSWORD: contraseña
    ports:
      - "5432:5432"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
